/-
# Toy Models

Model A: Directed chain (positive model)
Model B: DAG with incompatible metric (negative model)
Model C: Symmetric propagation (shows directedness is essential)

Also: Theorem 9 (same metric, different causal orders)
-/
import RequestProject.Compatibility

open Finset BigOperators Real

noncomputable section

/-! ## Model A: Directed Chain

S = Fin (n+1) = {0, 1, ..., n}
Propagation: K_1(i, i+1) = 1, K_1(i, j) = 0 otherwise
             K_t generated by semigroup law
Metric: d(i,j) = |i - j| (from I(i,j) = exp(-|i-j|))

Properties:
- ≺_K is exactly the usual order (i < j)
- Semigroup law generates longer reachability
- Diamonds are intervals
- Finite-speed condition holds with v = 1
-/

/-! ### Directed chain propagation kernel -/

/-- The directed chain propagation kernel on Fin (n+1).
    K_t(i,j) = 1 if j = i + t (as naturals, with bounds), 0 otherwise.
    This represents unit-speed forward propagation along the chain. -/
def chainK (n : ℕ) (t : ℕ) (i j : Fin (n + 1)) : ℝ :=
  if (j : ℕ) = (i : ℕ) + t ∧ (i : ℕ) + t ≤ n then 1 else 0

lemma chainK_nonneg (n : ℕ) (t : ℕ) (i j : Fin (n + 1)) :
    0 ≤ chainK n t i j := by
  unfold chainK; split_ifs <;> norm_num

/-
PROVIDED SOLUTION
chainK n 0 i j = if (j:ℕ) = (i:ℕ) + 0 ∧ (i:ℕ) + 0 ≤ n then 1 else 0. Note (i:ℕ) + 0 = (i:ℕ), and (i:ℕ) ≤ n is always true for i : Fin (n+1). So this equals if (j:ℕ) = (i:ℕ) then 1 else 0. And (j:ℕ) = (i:ℕ) iff i = j (by Fin.val_injective). So chainK n 0 i j = if i = j then 1 else 0.
-/
lemma chainK_identity (n : ℕ) (i j : Fin (n + 1)) :
    chainK n 0 i j = if i = j then 1 else 0 := by
      -- By definition of chainK, when t=0, we have j = i + 0, which simplifies to j = i.
      simp [chainK];
      grind +ring

/-
PROVIDED SOLUTION
We need chainK n (t+s) i j = ∑ k, chainK n t i k * chainK n s k j. chainK n t i k = 1 iff (k:ℕ) = (i:ℕ)+t and (i:ℕ)+t ≤ n, else 0. So the sum has at most one nonzero term, when k has value (i:ℕ)+t (if that's in range). The product chainK n t i k * chainK n s k j is nonzero only when k = i+t (in range) AND j = k+s = i+t+s (in range). In that case the product is 1. chainK n (t+s) i j = 1 iff j = i+t+s and i+t+s ≤ n. So both sides equal 1 when j = i+t+s and i+t+s ≤ n, and 0 otherwise. The tricky part is showing the sum equals this. Use Finset.sum_eq_zero when no valid k exists, or show the sum has exactly one term.
-/
lemma chainK_semigroup (n : ℕ) (t s : ℕ) (i j : Fin (n + 1)) :
    chainK n (t + s) i j = ∑ k : Fin (n + 1), chainK n t i k * chainK n s k j := by
      by_cases h_cases : (i : ℕ) + (t : ℕ) + (s : ℕ) ≤ n ∧ j = (i : ℕ) + (t : ℕ) + (s : ℕ);
      · rw [ Finset.sum_eq_single ( ⟨ ( i : ℕ ) + t, by linarith ⟩ : Fin ( n + 1 ) ) ] <;> simp +decide [ *, chainK ];
        · grind;
        · grind;
      · rw [ Finset.sum_eq_zero ];
        · exact if_neg fun h => h_cases ⟨ by linarith, by linarith ⟩;
        · unfold chainK;
          grind

/-- The directed chain as a PropagationKernel. -/
def chainPropKernel (n : ℕ) : PropagationKernel (Fin (n + 1)) where
  K := chainK n
  nonneg := chainK_nonneg n
  identity := chainK_identity n
  semigroup := chainK_semigroup n

/-
PROBLEM
The chain propagation kernel is acyclic.

PROVIDED SOLUTION
For i : Fin(n+1) and t > 0, chainK n t i i = if (i:ℕ) = (i:ℕ) + t ∧ (i:ℕ) + t ≤ n then 1 else 0. Since t > 0, (i:ℕ) ≠ (i:ℕ) + t, so the condition is false. Hence chainK n t i i = 0.
-/
theorem chain_acyclic (n : ℕ) : (chainPropKernel n).Acyclic := by
  intro i t ht; unfold chainPropKernel; unfold chainK at *; aesop;

/-
PROBLEM
The causal relation on the chain is exactly the strict order on Fin.

PROVIDED SOLUTION
Forward: causal i j means ∃ t > 0 with chainK n t i j > 0. chainK n t i j > 0 means (j:ℕ) = (i:ℕ) + t and (i:ℕ) + t ≤ n. Since t > 0, (j:ℕ) = (i:ℕ) + t > (i:ℕ), so (i:ℕ) < (j:ℕ). Backward: if (i:ℕ) < (j:ℕ), let t = (j:ℕ) - (i:ℕ). Then t > 0, (j:ℕ) = (i:ℕ) + t, and (i:ℕ) + t = (j:ℕ) ≤ n. So chainK n t i j = 1 > 0.
-/
theorem chain_causal_iff (n : ℕ) (i j : Fin (n + 1)) :
    (chainPropKernel n).causal i j ↔ (i : ℕ) < (j : ℕ) := by
      constructor <;> intro h;
      · obtain ⟨ t, ht_pos, ht ⟩ := h;
        unfold chainPropKernel at ht;
        unfold chainK at ht;
        grind;
      · use j - i;
        exact ⟨ Nat.sub_pos_of_lt h, by rw [ show ( chainPropKernel n ).K ( j - i ) i j = 1 from by { exact if_pos ⟨ by { omega }, by { omega } ⟩ } ] ; norm_num ⟩

/-! ### Chain correlation kernel -/

/-- Correlation kernel for the chain: I(i,j) = exp(-|i-j|). -/
def chainI (n : ℕ) (i j : Fin (n + 1)) : ℝ :=
  Real.exp (-(|(↑i : ℤ) - ↑j|))

/-
PROVIDED SOLUTION
chainI n i j = exp(-|i - j|). exp is always positive.
-/
lemma chainI_pos (n : ℕ) (i j : Fin (n + 1)) : 0 < chainI n i j := by
  exact Real.exp_pos _

/-
PROVIDED SOLUTION
chainI n i j = exp(-|i-j|). Since |i-j| ≥ 0, -|i-j| ≤ 0, so exp(-|i-j|) ≤ exp(0) = 1.
-/
lemma chainI_le_one (n : ℕ) (i j : Fin (n + 1)) : chainI n i j ≤ 1 := by
  exact Real.exp_le_one_iff.mpr ( by norm_num )

/-
PROVIDED SOLUTION
chainI n i i = exp(-|i-i|) = exp(-0) = exp(0) = 1.
-/
lemma chainI_diag (n : ℕ) (i : Fin (n + 1)) : chainI n i i = 1 := by
  unfold chainI; norm_num;

/-
PROVIDED SOLUTION
chainI n i j = exp(-|i-j|) = exp(-|j-i|) = chainI n j i, since |i-j| = |j-i| (absolute value is symmetric).
-/
lemma chainI_symm (n : ℕ) (i j : Fin (n + 1)) : chainI n i j = chainI n j i := by
  unfold chainI; simp +decide [ abs_sub_comm ] ;

/-
PROVIDED SOLUTION
chainI n i k = exp(-|i-k|) and chainI n i j * chainI n j k = exp(-|i-j|) * exp(-|j-k|) = exp(-(|i-j|+|j-k|)). We need exp(-|i-k|) ≥ exp(-(|i-j|+|j-k|)). Since exp is monotone and |i-k| ≤ |i-j| + |j-k| (triangle inequality for absolute value on ℤ), we have -|i-k| ≥ -(|i-j|+|j-k|), so exp(-|i-k|) ≥ exp(-(|i-j|+|j-k|)). Use abs_sub_abs_le_abs_sub or the integer triangle inequality.
-/
lemma chainI_supermul (n : ℕ) (i j k : Fin (n + 1)) :
    chainI n i k ≥ chainI n i j * chainI n j k := by
      unfold chainI;
      norm_num [ ← Real.exp_add ];
      grind +splitImp

/-- The chain correlation kernel. -/
def chainCorrKernel (n : ℕ) : CorrelationKernel (Fin (n + 1)) where
  I := chainI n
  pos := chainI_pos n
  le_one := chainI_le_one n
  diag := chainI_diag n
  symm := chainI_symm n
  supermul := chainI_supermul n

/-
PROBLEM
Finite-speed propagation holds for the chain with v = 1.

PROVIDED SOLUTION
We need FiniteSpeedPropagation (chainCorrKernel n) (chainPropKernel n) 1, which means 0 < 1 and for all t i j, K t i j > 0 → d(i,j) ≤ 1*t. If chainK n t i j > 0, then (j:ℕ) = (i:ℕ) + t and (i:ℕ) + t ≤ n. d(i,j) = -log(exp(-|i-j|)) = |i-j| (since log(exp(x)) = x for appropriate x and |i-j| ≥ 0 so -|i-j| ≤ 0). Here |i-j| = |(i:ℤ) - (j:ℤ)| = |-(t:ℤ)| = t. So d(i,j) = t ≤ 1*t. Actually we need to be more careful with the log computation since chainI involves integer absolute value cast to ℝ. The key point is d(i,j) = |i-j| = t ≤ t = 1*t.
-/
theorem chain_finite_speed (n : ℕ) :
    FiniteSpeedPropagation (chainCorrKernel n) (chainPropKernel n) 1 := by
      constructor;
      · norm_num;
      · intro t i j h; rw [ chainCorrKernel ] ; unfold CorrelationKernel.d;
        unfold chainI chainPropKernel at *;
        unfold chainK at h ; aesop

/-! ## Model B: DAG with incompatible metric (counterexample)

This is essentially the counterexample for Theorem 6 / Assumption C.
See Compatibility.lean for the formal statement.
-/

/-! ## Model C: Symmetric propagation

Construct a kernel with K_t(i,j) = K_t(j,i) for some t > 0,
yielding bidirectional reachability. Show acyclicity fails.
-/

/-- A symmetric propagation kernel on Fin 2: K_1(0,1) = K_1(1,0) = 1. -/
def symK (t : ℕ) (i j : Fin 2) : ℝ :=
  if t = 0 then (if i = j then 1 else 0)
  else 1  -- all entries positive for t > 0

/-- The symmetric kernel has K_1(i,j) = K_1(j,i). -/
lemma symK_symmetric (i j : Fin 2) : symK 1 i j = symK 1 j i := by
  simp [symK]

/-
PROBLEM
With symmetric propagation, there exist cycles: K_1(0,0) > 0 when
    we sum over the intermediate node. However, we directly show that
    the induced causal relation is reflexive, proving acyclicity fails.

PROVIDED SOLUTION
Use S = Fin 2. Define K as: K 0 i j = if i = j then 1 else 0; K t i j = 1 for all t > 0. Then K_1(i,j) = 1 = K_1(j,i) (symmetric). Also K is not acyclic because K_1(0,0) = 1 > 0. For the semigroup law: K(t+s)(i,j) = ∑_k K(t)(i,k)*K(s)(k,j). When t > 0 and s > 0: K(t+s)(i,j) = 1, and ∑_k K(t)(i,k)*K(s)(k,j) = ∑_k 1*1 = |S| = 2. That doesn't work since we need equality.

Instead, use S = Fin 1 (single element). K 0 0 0 = 1, K t 0 0 = 1 for all t. Semigroup: K(t+s)(0,0) = ∑_{k:Fin 1} K(t)(0,k)*K(s)(k,0) = K(t)(0,0)*K(s)(0,0) = 1*1 = 1. ✓ Symmetric: K_1(i,j) = K_1(j,i) = 1. ✓ Not acyclic: K_1(0,0) = 1 > 0. ✓
-/
theorem symmetric_propagation_has_self_loops :
    ∃ (S : Type) (_ : Fintype S) (_ : DecidableEq S) (P : PropagationKernel S),
      (∀ i j : S, P.K 1 i j = P.K 1 j i) ∧ ¬P.Acyclic := by
        norm_num [ PropagationKernel.Acyclic ];
        refine' ⟨ _, _, _, _, _, _ ⟩;
        exact Fin 1;
        all_goals try infer_instance;
        refine' ⟨ fun t i j => if t = 0 then if i = j then 1 else 0 else 1, _, _, _ ⟩ <;> norm_num;
        · lia;
        · exact ⟨ 0, 1, by norm_num ⟩

/-! ## Theorem 9: Same metric, different causal orders -/

/-
PROBLEM
There exist two propagation kernels on the same type with the same
    correlation kernel but different causal orders.

PROVIDED SOLUTION
Use S = Fin 3. Define P₁ as the chain propagation 0→1→2 (i.e. chainPropKernel 2, which gives causal 0 1, causal 1 2, causal 0 2). Define P₂ as the chain in the other direction: K_t(i,j) = 1 if (i:ℕ) = (j:ℕ) + t (i.e. propagation backwards 2→1→0). Then P₁.causal 0 1 holds but P₂.causal 0 1 does not (since in P₂, propagation goes from higher to lower indices). Both are acyclic.

Actually simpler: use S = Fin 2. P₁ has K_1(0,1) = 1 (forward), P₂ has K_1(1,0) = 1 (backward). Both satisfy semigroup (single step each direction). P₁.causal 0 1 holds, P₂.causal 0 1 does not (P₂ only propagates 1→0). Both are acyclic.

For P₁: K 0 i j = if i=j then 1 else 0. K t 0 1 = 1 if t=1, else K t i j computed via semigroup. Actually let me use t = distance: K t i j = 1 if j = i+t and i+t ≤ 1, else 0. So K 1 0 1 = 1, everything else 0 for t > 0 on Fin 2. Semigroup works the same as chainK.

For P₂: K t i j = 1 if (i:ℕ) = (j:ℕ) + t and (j:ℕ) + t ≤ 1, else 0 for t > 0. So K 1 1 0 = 1 (since 1 = 0+1 and 0+1 ≤ 1). P₂.causal 1 0 holds. P₂.causal 0 1 doesn't hold (K t 0 1 would need 1 = 0+t → t=1, but also 0+1 ≤ 1 ✓ wait... in P₂ the condition is (i:ℕ) = (j:ℕ)+t, so for i=0,j=1: 0 = 1+t, impossible for t:ℕ).

Both are acyclic: P₁.K t i i = 0 for t > 0 (since i ≠ i+t for t>0), same for P₂ (i = i+t impossible for t>0).

Use P₁ = chainPropKernel 1, i = (0 : Fin 2), j = (1 : Fin 2). P₁.causal 0 1 holds.
For P₂, define a reversed chain propagation kernel.
-/
theorem same_metric_different_causality :
    ∃ (S : Type) (_ : Fintype S) (_ : DecidableEq S)
      (P₁ P₂ : PropagationKernel S),
      P₁.Acyclic ∧ P₂.Acyclic ∧
      ∃ (i j : S), P₁.causal i j ∧ ¬P₂.causal i j := by
        -- Let's choose S = Fin 2.
        use Fin 2;
        fconstructor;
        exact inferInstance;
        use inferInstance, chainPropKernel 1, chainPropKernel 1 |> fun P => ⟨ fun t i j => P.K t ( Fin.rev i ) ( Fin.rev j ), by
          exact fun t i j => P.nonneg t _ _, by
          simp +decide [ P.identity ], by
          intro t s i j; convert P.semigroup t s ( Fin.rev i ) ( Fin.rev j ) using 1; simp +decide [ Finset.sum_range_succ, Finset.sum_range_zero ] ; ring; ⟩
        generalize_proofs at *;
        refine' ⟨ _, _, _ ⟩
        all_goals generalize_proofs at *;
        · grind +suggestions;
        · intro i t ht; have := chain_acyclic 1; aesop;
        · use 0, 1; simp +decide [ chainPropKernel ] ;
          unfold PropagationKernel.causal; simp +decide [ chainK ] ;
          exact ⟨ ⟨ 1, by norm_num ⟩, fun x hx => by split_ifs <;> linarith ⟩

end